using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Blog.Data.Mappings;


public class PostMap : IEntityTypeConfiguration<Post>
{
    public void Configure(EntityTypeBuilder<Post> builder)
    {
         // configure the table
        builder.ToTable("User");

        // defines the primary key using a lambda function
        builder.HasKey(x=>x.Id);

        // the Id will be generated by the code every time we add a new Post
        builder.Property(x=>x.Id)
        .ValueGeneratedOnAdd()
        .UseIdentityColumn(); // Identity (1,1)

        builder.Property(x => x.LastUpdateDate)
        .IsRequired()
        .HasColumnName("LastUpdateData")
        .HasColumnType("SMALLDATETIME")
        //.HasDefaultValueSql("GETDATE()")
        .HasDefaultValue(DateTime.Now.ToUniversalTime());

        builder.Property(x=>x.Slug)
        .IsRequired()
        .HasColumnName("Slug")
        .HasColumnType("NVARCHAR")
        .HasMaxLength(80);

        // Index
        builder.HasIndex(x=>x.Slug, "IX_Category_Slug")
        .IsUnique();

    }
}